version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: "mongodb://mongo:27017/mydatabase"
      AWS_ACCESS_KEY_ID: ${AKIAQLSIVKBOUUOVN5NM}
      AWS_SECRET_ACCESS_KEY: ${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}
      AWS_S3_BUCKET: "satheesh-s3bucket"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
